### PR TITLE
Updated nxlog to version 2.10.2150

### PR DESCRIPTION
**Pull request by nick4eva**

### CODE REVIEW

**Comment by nick4eva** [comment]
@petemounce could you please merge?

**Comment by nick4eva** [comment]
@petemounce or @jamescrowley or @kurtglastetter could you please merge this PR, since it's published on Chocolatey long time ago.

**Comment by petemounce** [comment]
@jamescrowley I cannot invite @nick4eva (but can vouch for him as a previous colleague :) ); please would you grant him push access?

**Comment by jamescrowley** [comment]
@petemounce apologies for the delay, but I've added @nick4eva . I don't think there's a way for me to give you more permissions @petemounce on a personal public repo? But let me know if there is!

**Comment by petemounce** [comment]
In settings/collaborators, make us admins I think.

**Comment by jamescrowley** [comment]
@petemounce only works for orgs, I think.

Screenshot 2019-09-09 at 10 19 01

**Comment by petemounce** [comment]
Oooh. OK.

**Comment by jamescrowley** [comment]
@petemounce feel free to fork/switch Chocolately away from this repo though if needed! I haven't used NXLog in some time.

**Comment by petemounce** [comment]
Me either. Maybe transfer it to @nick4eva ?

**Comment by nick4eva** [comment]
Agree, we're still using nxlog.

**Comment by jamescrowley** [comment]
@nick4eva I think you have all the maintainer permissions on Chocolatey, I have no problem if you  re-point to a forked repo elsewhere. If you need anything from me just let me know.

**Pull request merged**
